services:
  api:
    build: .
    image: event-planner-api:latest
    ports:
      - "8100:8100"
    env_file:
      - .env.prod

    datatabse:
      image: mongo:5.0.15
      ports:
        - "27017"
      volumes:
        - data:/data/db

volumes:
  data: